name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", " triage"]
projects: ["sem"]
assignees:
- isendra
-  alicenur04
-  maja4h
-  LeoEggett
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if you need more info?
      placeholder: some@email.com
    validations: 
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you think or expect to happen.
      placeholder: Tell us what you see.
      value: "A bug happened!"
    validations:
      required: true








      
  
